    - |
      apt update && apt install git wget curl rsync -y
      git config --global --add safe.directory $CI_PROJECT_DIR  && pwd

    - |
      # Install nodejs and composer
      echo "Node v${NODE_VERSION} will be installed"
      nodejs_upstream_url="https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz"
    - wget -qO- ${nodejs_upstream_url} | tar -xJ -C /usr/local --strip-components=1
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - command -v node || $(echo "node not found" && exit 1)
    - echo "`node --version` && `npm --version`"
    - npm install --global yarn
