# https://taskfile.dev

version: "3"

env:
  REGISTRY: "ghcr.io/smile-oss"

tasks:
  build:
    aliases:
      - "default"
    desc: Build docker image
    summary: |
      Build docker image

      You should pass the following arguments:
      - Version: Desired PHP version

      Example:
      ❯ task build Version=8.1

    dir: "{{.USER_WORKING_DIR}}/docker/{{.Version}}"
    cmds:
      - >
        docker build . -t ${REGISTRY}/php-node:{{.Version}}
      - echo "Built ${REGISTRY}/php-node:{{.Version}}"

  push:
    desc: Push docker image
    summary: |
      Push docker image

      You should pass the following arguments:
      - Version: Desired PHP version

      Example:
      ❯ task push Version=8.1

    dir: "{{.USER_WORKING_DIR}}/docker/{{.Version}}"
    cmds:
      - >
        docker push ${REGISTRY}/php-node:{{.Version}}
      - echo "Pushed ${REGISTRY}/php-node:{{.Version}}"
