name: build-n-push

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/docker-login
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Build and push Docker image
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: Build Docker image
        run: |
          ls -lha . && pwd
          echo "Build the image"
          task build-all Tag="${{ github.ref_name }}"

      - name: Push Docker image
        run: |
          echo "Push the image"
          task push-all Tag="${{ github.ref_name }}"
